### ISSUE TITLE
时间尺子显示时间页面的最右侧的时间能否显示为23:59:59

### ISSUE THREAD

**Issue by SeasonHe** [specialgirlgotoheaven/time-Schedule#11]
![image](https://cloud.githubusercontent.com/assets/10720967/21563679/64c4eee4-cebf-11e6-811f-dc0beea8ccf5.png)

**Comment by specialgirlgotoheaven** [comment]
对最后一个做单独处理
            if(i == num_steps){
                this.$ruler.append(
                    '<div id="graduation-title-hour' + i + '" class="graduation-title' + (caret_class ? '' : ' hidden') + '" style="left:' + (left - leftMove).toString() + 'px">' +
                    '23:59:59' +
                    '</div>'
                );
            }else{
                this.$ruler.append(
                    '<div id="graduation-title-hour' + i + '" class="graduation-title' + (caret_class ? '' : ' hidden') + '" style="left:' + (left - leftMove).toString() + 'px">' +
                    this.graduation_title(date) +
                    '</div>'
                );
            }
